// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";
import { group } from "k6";

export let options = {
  scenarios: {

    smoke: {
      executor: 'constant-vus',
      vus: 3,
      duration: '20s',
      tags: { test_type: 'smoke' },
    },

    load: {
      executor: 'constant-vus',
      vus: 25,
      duration: '40s',
      tags: { test_type: 'load' },
    },
  },

  thresholds: {
    http_req_duration: ['p(95)<2000'],
    http_req_failed: ['rate<0.01'],
  },
};


const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    baseUrl: "https://dummyjson.com",
    token: "",
    productId: ""
  }
});

export default function() {
  group("auth", function() {
    postman[Request]({
      name: "Login",
      id: "1b8294d3-6adb-437f-9138-ba263403bd7c",
      method: "POST",
      address: "{{baseUrl}}/auth/login",
      data: '{\n  "username": "emilys",\n  "password": "emilyspass"\n}\n',
      post(response) {
        pm.test("Login success status", function() {
          pm.response.to.have.status(200);
        });

        pm.test("Response time OK", function() {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });

        pm.environment.set("token", pm.response.json().accessToken);
      }
    });

    postman[Request]({
      name: "Login (invalid input)",
      id: "af21815f-fcad-4a29-b4f2-54096a403cb5",
      method: "POST",
      address: "{{baseUrl}}/auth/login",
      data: '{\n  "username": "maitaha",\n  "password": "emilyspass"\n}\n',
      post(response) {
        pm.test("Invalid login returns error", function() {
          pm.expect(pm.response.code).to.be.oneOf([400, 401]);
        });

        pm.test("Error message exists", function() {
          pm.expect(pm.response.text()).to.not.be.empty;
        });
        pm.environment.set("token", pm.response.json().accessToken);
      }
    });
  });

  group("products", function() {
    postman[Request]({
      name: "Get Products",
      id: "8ca6cac4-a98e-4f84-8d13-7f485e500b43",
      method: "GET",
      address: "{{baseUrl}}/products",
      post(response) {
        pm.test("Status 200", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Products returned", () => {
          pm.expect(pm.response.json()).to.have.property("products");
        });

        pm.test("Response time OK", () => {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Get Products (limits)",
      id: "122bd8a4-71f0-4f02-8a35-5f683f19a3ad",
      method: "GET",
      address: "{{baseUrl}}/products?limit=5",
      post(response) {
        pm.test("Status 200", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Products returned", () => {
          pm.expect(pm.response.json()).to.have.property("products");
        });

        pm.test("Response time OK", () => {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Get Products (skip)",
      id: "e025dde8-2e85-4d4a-9e77-53b4531699c8",
      method: "GET",
      address: "{{baseUrl}}/products?skip=10",
      post(response) {
        pm.test("Status 200", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Products returned", () => {
          pm.expect(pm.response.json()).to.have.property("products");
        });

        pm.test("Response time OK", () => {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Get Product by id",
      id: "21df424b-05b7-4cfd-858c-27e6c6066a47",
      method: "GET",
      address: "{{baseUrl}}/products/10",
      post(response) {
        pm.test("Status 200", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Response time OK", () => {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Get Product by id (Invalid input)",
      id: "61c3a488-ca6a-4eb1-9884-0d2ca1b975d8",
      method: "GET",
      address: "{{baseUrl}}/products/1234",
      post(response) {
        pm.test("Invalid product id handled", () => {
          pm.response.to.have.status(404);
        });
        pm.test("Error or empty result", function() {
          pm.expect(pm.response.text()).to.not.be.empty;
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Get Product Categories",
      id: "90fe47b6-a9b9-4252-961f-5ab7832549ad",
      method: "GET",
      address: "{{baseUrl}}/products/categories",
      post(response) {
        pm.test("Status 200", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Response time OK", () => {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Get Product by Category",
      id: "040ca6fe-c0b8-4bb7-b63d-947bdd198a46",
      method: "GET",
      address: "{{baseUrl}}/products/category/beauty",
      post(response) {
        pm.test("Status 200", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Products returned", () => {
          pm.expect(pm.response.json()).to.have.property("products");
        });

        pm.test("Response time OK", () => {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Add Product",
      id: "6bd72813-b377-42b7-882a-c6d05a545bcb",
      method: "POST",
      address: "{{baseUrl}}/products/add",
      data:
        '{\n  "title": "Mai Test Product ",\n  "price": 100,\n  "description": "Added Product For API Testing  ",\n  "category": "laptops"\n\n}\n',
      post(response) {
        pm.test("Product added", () => {
          pm.response.to.have.status(201);
        });

        pm.test("Product id exists", () => {
          pm.expect(pm.response.json().id).to.exist;
        });

        pm.test("Title exists", () => {
          pm.expect(pm.response.json()).to.have.property("title");
        });

        pm.environment.set("productId", pm.response.json().id);
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "patch Product",
      id: "a49131c6-bd7b-40ce-880a-2f6b60e722a1",
      method: "PATCH",
      address: "{{baseUrl}}/products/1",
      data: '{\n  "price": 555\n}\n',
      post(response) {
        pm.test("Update success", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Updated fields returned", () => {
          pm.expect(pm.response.text()).to.not.be.empty;
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Update Product",
      id: "45ee44e2-45a0-44d1-bf24-bef4e2001ee9",
      method: "PUT",
      address: "{{baseUrl}}/products/2",
      data: '{\n  "title": "Updated Test Product",\n  "price": 300\n}\n',
      post(response) {
        pm.test("Update success", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Updated fields returned", () => {
          pm.expect(pm.response.text()).to.not.be.empty;
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Update Product (invalid input)",
      id: "d2351e52-4417-47c8-84f4-2c5c2a352abf",
      method: "PUT",
      address: "{{baseUrl}}/products/678",
      data: '{\n  "title": "Updated Test Product",\n  "price": 300\n}\n',
      post(response) {
        pm.test("Invalid update handled", () => {
          pm.response.to.have.status(404);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Delete Product",
      id: "ee317749-7dba-4deb-b2ac-206b5d830bca",
      method: "DELETE",
      address: "{{baseUrl}}/products/1",
      post(response) {
        pm.test("Delete success", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Delete response returned", () => {
          pm.expect(pm.response.text()).to.not.be.empty;
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Delete Product (Invalid input)",
      id: "102bd3a0-3159-403c-9b95-3108157270ab",
      method: "DELETE",
      address: "{{baseUrl}}/products/99999",
      post(response) {
        pm.test("Invalid delete handled", () => {
          pm.response.to.have.status(404);
        });
      }
    });

    postman[Request]({
      name: "Search Products",
      id: "2eda6e47-09fb-4247-b161-6200d76478c4",
      method: "GET",
      address: "{{baseUrl}}/products/search?q=phone",
      post(response) {
        pm.test("Status 200", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Products returned", () => {
          pm.expect(pm.response.json()).to.have.property("products");
        });

        pm.test("Response time OK", () => {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Search Products (Invalid input)",
      id: "46ef59b0-ab86-4b88-b1d3-87c9e12219f0",
      method: "GET",
      address: "{{baseUrl}}/products/search?q=zzzzzzz",
      post(response) {
        pm.test("Invalid search handled", () => {
          pm.response.to.have.status(200);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Get Users",
      id: "5640ac98-1622-4b5f-89a6-addc15acb97e",
      method: "GET",
      address: "{{baseUrl}}/users",
      post(response) {
        pm.test("Status 200", function() {
          pm.response.to.have.status(200);
        });

        pm.test("Users returned", function() {
          pm.expect(pm.response.text()).to.not.be.empty;
        });

        pm.test("Response time OK", function() {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });
  });

  group("cart", function() {
    postman[Request]({
      name: "Get cart",
      id: "e5f48710-c425-41df-9993-202dd9d38f52",
      method: "GET",
      address: "{{baseUrl}}/carts",
      post(response) {
        pm.test("Cart fetched", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Cart data exists", () => {
          pm.expect(pm.response.text()).to.not.be.empty;
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Add cart",
      id: "9d3a803f-5725-4ef4-830e-b85fd300b05f",
      method: "POST",
      address: "{{baseUrl}}/carts/add",
      data:
        '{\n  "userId": 1,\n  "products": [\n    {\n      "id": 1,\n      "quantity": 2\n    }\n  ]\n}\n',
      post(response) {
        pm.test("Cart added", () => {
          pm.response.to.have.status(201);
        });

        pm.test("Cart id exists", () => {
          pm.expect(pm.response.json().id).to.exist;
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });
  });
}
