// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    baseUrl: "https://dummyjson.com",
    token: "",
    productId: ""
  }
});

export default function() {
  group("products", function() {
    postman[Request]({
      name: "Get Products",
      id: "77a89353-4f83-4cc8-b3a6-6caee192f6a8",
      method: "GET",
      address: "{{baseUrl}}/products",
      post(response) {
        pm.test("Status 200", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Products returned", () => {
          pm.expect(pm.response.json()).to.have.property("products");
        });

        pm.test("Response time OK", () => {
          pm.expect(pm.response.responseTime).to.be.below(2000);
        });
        pm.test("Response schema is valid", function() {
          const jsonData = pm.response.json();
          pm.expect(jsonData).to.have.property("products");
          pm.expect(jsonData.products).to.be.an("array");
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Add Product",
      id: "1aa51417-e43c-4c4e-91c0-04b13ba3c80e",
      method: "POST",
      address: "{{baseUrl}}/products/add",
      data:
        '{\n  "title": "Mai Test Product ",\n  "price": 100,\n  "description": "Added Product For API Testing  ",\n  "category": "laptops"\n\n}\n',
      post(response) {
        pm.test("Product added", () => {
          pm.response.to.have.status(201);
        });

        pm.test("Product id exists", () => {
          pm.expect(pm.response.json().id).to.exist;
        });

        pm.test("Title exists", () => {
          pm.expect(pm.response.json()).to.have.property("title");
        });

        pm.environment.set("productId", pm.response.json().id);
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });

    postman[Request]({
      name: "Delete Product",
      id: "cfb7b515-0be6-4eba-959d-ce3fbff128a3",
      method: "DELETE",
      address: "{{baseUrl}}/products/1",
      post(response) {
        pm.test("Delete success", () => {
          pm.response.to.have.status(200);
        });

        pm.test("Delete response returned", () => {
          pm.expect(pm.response.text()).to.not.be.empty;
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("token")}`;
      }
    });
  });
}
